messenger:
    transports:
        netgen_ibexa_search_extra_asynchronous_indexing:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failure_transport: netgen_ibexa_search_extra_asynchronous_indexing_failed
            retry_strategy:
                max_retries: 5
                delay: 1000
                multiplier: 3
                max_delay: 600000
            options:
                redeliver_timeout: 300
                queue_name: netgen_ibexa_search_extra_asynchronous_indexing
        netgen_ibexa_search_extra_asynchronous_indexing_failed: "doctrine://default?queue_name=netgen_ibexa_search_extra_asynchronous_indexing_failed"
    default_bus: messenger.bus.default
    buses:
        messenger.bus.default: ~
