name: Tests

on:
    push:
        branches:
            - 'master'
            - '[0-9].[0-9]+'
    pull_request: ~

jobs:
    tests:
        name: ${{ matrix.php }} ${{ matrix.coverage }} ${{ matrix.engine }} ${{ matrix.solr_version }} ${{ matrix.regression }} ${{ matrix.core_setup }}
        runs-on: ubuntu-latest
        env:
            extensions: pdo_sqlite

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php: '8.1'
                      coverage: 'unit'
                      config: 'phpunit.xml'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'legacy'
                      config: 'phpunit-integration-legacy.xml'

                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '7.7.3'
                      solr_cores: 'collection1'
                      core_setup: 'single'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '7.7.3'
                      core_setup: 'dedicated'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '7.7.3'
                      core_setup: 'shared'

                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '7.7.3'
                      solr_cloud: 'yes'
                      core_setup: 'cloud'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '7.7.3'
                      solr_cloud: 'yes'
                      solr_config: 'vendor/ibexa/solr/src/lib/Resources/config/solr/schema.xml vendor/ibexa/solr/src/lib/Resources/config/solr/language-fieldtypes.xml tests/lib/Resources/config/search/solr/8.11/solrconfig.xml tests/lib/Resources/config/search/solr/custom-fields-types.xml'
                      core_setup: 'cloud'

                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      solr_cores: 'collection1'
                      core_setup: 'single'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'dedicated'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      core_setup: 'shared'

                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      solr_cloud: 'yes'
                      core_setup: 'cloud'
                    - php: '8.1'
                      coverage: 'integration'
                      engine: 'solr'
                      config: 'phpunit-integration-solr.xml'
                      solr_version: '8.11.2'
                      solr_cloud: 'yes'
                      solr_config: 'vendor/ibexa/solr/src/lib/Resources/config/solr/schema.xml vendor/ibexa/solr/src/lib/Resources/config/solr/language-fieldtypes.xml tests/lib/Resources/config/search/solr/8.11/solrconfig.xml tests/lib/Resources/config/search/solr/custom-fields-types.xml'
                      core_setup: 'cloud'

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 8
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}

            - run: composer --version
            - run: composer validate --strict
            - run: composer update --prefer-dist
            - run: ./bin/init_solr.sh
              env:
                  SOLR_VERSION: ${{ matrix.solr_version }}
                  SOLR_CLOUD: ${{ matrix.solr_cloud }}
                  SOLR_CONFIG: ${{ matrix.solr_config }}
                  SOLR_CORES: ${{ matrix.solr_cores }}
              if: matrix.solr_version
            - run: CORES_SETUP=${{ matrix.core_setup }} vendor/bin/phpunit --bootstrap tests/bootstrap.php -c ${{ matrix.config }} --colors=always
              env:
                  CORES_SETUP: ${{ matrix.core_setup }}
                  SOLR_CLOUD: ${{ matrix.solr_cloud }}
